services:
  api:
    build:
      context: https://github.com/lingfish/truenas-http-bridge.git
      tags:
        - "truenas-http-bridge:latest"
    environment:
      TRUENAS_API_KEY: # Your TrueNAS API key
      TRUENAS_API_USER: # Your TrueNAS API user
      TRUENAS_HOST: # TrueNAS host
      BRIDGE_API_USER: # The bridge API username
      BRIDGE_API_PASSWORD: # The bridge API password
      API_PORT: # Your chosen API port
      TZ: # Your timezone
    group_add:
      - 568
    hostname: truenas-http-bridge
    platform: linux/amd64
    ports:
      - '8000:8000'
    privileged: False
    pull_policy: always
    restart: 'unless-stopped'
    stdin_open: False
    tty: False
x-notes: |-
  # truenas-http-bridge

  ## Security
  Be aware that this app gives any and all access to the TrueNAS API!

  ## Bug reports and feature requests

  If you find a bug in this app or have an idea for a new feature, please file an issue at
  https://github.com/lingfish/truenas-http-bridge/issues
